config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only:[:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  
  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "投稿を作成しました"
      else
        render 'new'
      end
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice:"投稿を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "投稿を削除しました"
  end

  def confirm
    @picture = Picture.new(picture_params)
    render :new if @picture
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  private

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, except:[:new, :create, :destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show]
  # before_action :redirect_session, only: [:show]
  # before_action :login_new, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id])
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def redirect_session
    if @user.id != current_user.id 
      flash[:notice] = "権限がありません"
      redirect_to user_path(current_user.id)
    end
  end

  def login_new
    if logged_in? && !current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if current_user == nil
      redirect_to root_path
    end
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiromatsubook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
  </head>
  <body>
    <header>
      <div class="app_name"><a href="#">HIROMATSUBOOK</a></div>
      <div class="header_manu">
        <% if logged_in? %>
          <div class="profile"><%= link_to "マイページ", user_path(current_user.id) %></div>
          <div class="new_post"><%= link_to "投稿画面", new_picture_path(current_user.id) %></div>
          <div class="logout"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></div>
          <div class="crrent_user">ユーザー名：<%= current_user.name %></div>
        <% else %>
          <div class="sign_up"><%= link_to "新規登録", new_user_path %></div>
          <div class="login"><%= link_to "ログイン", new_session_path %></div>
        <% end %>
      </div>
    </header>
    <% flash.each do |key,value| %>
    <%= content_tag(:div,value,class:"#{key}")%>
    <% end %>
        <%= yield %>
        <footer>
          <div>
            <li>HIROMATSUBOOK</li>
            <li>© 2019 Copyright MATSUSE</li>
          </div>
        </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, url: choose_new_or_edit, local: true) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <br>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache%>
  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache%>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<p><%= notice %></p>

  <div class="contents">
    <% @pictures.each do |picture| %>

    <div class="index_picture">
      <div class="index_user_name">ユーザー名：<%= picture.user.name %></div>
      <%= image_tag picture.image.url if picture.image.url %>
      <div class=""><%= picture.content if picture.content %></div>


      <div class="index_picture_menu">
          <div class="index_show"><%= link_to '詳細', picture_path(picture.id) %></div>
          <div class="index_edit"><%= link_to "編集", edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' } %></div>
          <div class="index_destroy"><%= link_to '削除', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></div>
      </div>
    </div>
    <br>
    <% end %>

  </div>

app/views/pictures/new.html.erb
<h2>投稿する</h2>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>

<%= image_tag @picture.image.url if @picture.image.url %>
<%= @picture.content if @picture.content %>

  <div class="show_edit"><%= link_to '編集', edit_picture_path %></div>
  <div class="show_to_back"><%= link_to '戻る', pictures_path %></div>
  <div class="favorite">
    <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  </div>

<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/users/new.html.erb
<div class="main-container ">
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<p>メールアドレス: <%= @user.email %></p>

<%= link_to "投稿一覧画面へ", pictures_path %>